server:
  port: 7988
spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/jpa-demo
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
